name: Publish Containers

on:
  push:
    branches:
      - 'main'

jobs:

  build-publish-win:
    name: Create containers
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Get services
        working-directory: ./boba_ops
        run: git submodule sync --recursive && git submodule update --recursive --init

      - name: Build the services
        working-directory: ./boba_ops
        run: docker compose build && docker image rm -f bobanetwork/safe-react

      - name: Tag
        working-directory: ./boba_ops
        run: |
          docker images
          for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep bobanetwork); do
            docker image tag "$i" bobanetwork/$(echo $i | awk -F'/' '{print $2}' | awk -F':' '{print $1}'):latest
          done
          docker images

      - name: Push
        working-directory: ./boba_ops
        run: |
          for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep bobanetwork); do
            echo "$1"
            docker push "$i"
          done

      #separate building for mainnet and rinkeby frontends
      - name: Build safe-react Mainnet
        working-directory: ./boba_ops
        run: docker compose -f docker-compose.yml -f docker-compose.mainnet.yml build safe-react

      - name: Tag and Push
        working-directory: ./boba_ops
        run: |
          docker images
          docker image tag bobanetwork/safe-react bobanetwork/safe-react-mainnet:latest
          docker push bobanetwork/safe-react-mainnet:latest
      
      - name: Build safe-react Rinkeby
        working-directory: ./boba_ops
        run: docker compose -f docker-compose.yml -f docker-compose.rinkeby.yml build safe-react

      - name: Tag and Push
        working-directory: ./boba_ops
        run: |
          docker images
          docker image tag bobanetwork/safe-react bobanetwork/safe-react-rinkeby:latest
          docker push bobanetwork/safe-react-rinkeby:latest
